import { VStack } from "@chakra-ui/react";
import Head from "next/head";
import GridLayout from "../components/gridLayout";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Unsplash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack overflowX="hidden">
        <Navbar />
        <GridLayout />
      </VStack>
    </div>
  );
}
